language: java
dist: trusty

jdk:
  - openjdk11

addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver

cache:
  directories:
    - "${HOME}/.m2/"

stages:
  - compile
  - test
  - deploy

install: true

script: mvn test

before_script:
  - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"